### ISSUE TITLE
老哥还更新吗？

### ISSUE THREAD

**Issue by 18230** [ayuayue/chatgpt_token_vercel#1]

**Comment by ayuayue** [comment]
> 

更新啊，加了官方账号直登的，有什么问题吗

**Comment by 18230** [comment]
我试了下 返回："Access Token not found in the response."

**Comment by ayuayue** [comment]
> 我试了下 返回："Access Token not found in the response."

好的，我看下什么原因，尽快修复

**Comment by ayuayue** [comment]
> 我试了下 返回："Access Token not found in the response."

已修复，如果是调用的自己部署的pandora服务，需要重新部署下pandora的服务，如果是用的我的服务，那可以无视，直接使用即可

**Comment by 18230** [comment]
感谢老哥


caoayu ***@***.***> 于2023年7月16日周日 13:30写道：
